# Doc - https://github.com/marketplace/actions/auto-author-assign
name: "✋ Pull Request Auto Assignee"

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.1